### ISSUE TITLE
Dropdown text should change and reflect the selected item under it.

### ISSUE THREAD

**Issue by alexandruboboc** [pippogsm/droptabs#1]
When selecting an item from the dropdown, there is no feedback for the user regarding selected element, unless the dropdown is again expanded.

The dropdown text should change and show the selected item text.

**Comment by dirko0816** [comment]
there ist an issue on this:

if the original dropdown-text is smaller then the changed wording the dropdown-tab increases its width.
If theres not enough space in tabpanel, the last original tab (the one prior to the dropdown-tab) is not added to the dropdown-menue - it moves to the next line.
